#!/usr/bin/env bash

while [ true ]

do 
#first, we make sure we have network ON. This script had failed before, even after network.target
	ping -c 1 google.com > /dev/null
	if [ $? -ne 0  ]
	then 
		echo "Ping failed. Waiting for network up."
	else

#then we grab the public IP
		
		ip=$(/usr/bin/dig +short myip.opendns.com @resolver3.opendns.com.)

# I know. 
# This looks like an exercise in cut, but it's not. 
# Just the simplest way I could think of.

# Then we create the message variables

uptime=`uptime | cut -d" " -f3-5 | cut -d"," -f1`
srvtime=`uptime | cut -d" " -f2`
logins=`uptime | cut -d" " -f7-8 | cut -d"," -f1`
load=`uptime | cut -d":" -f4 | cut -d" " -f2-`
users=`who | cut -d' ' -f1-4,14`

# We then create the message and send the email
		echo -e "to: example@gmail.com\nSubject:$(hostname) is online.\nPublic IP:\n$ip\n\nLocal Server Time:\n$srvtime\n\nServer Uptime:\n$uptime\n\nUser Login Count:\n$logins\n\nOpen Sessions:\n$users\n\nLoad Average:\n$load" | /usr/sbin/sendmail -t -f root 

		exit 0
	fi
	sleep 1
# loop de loop
done
# voila
