#!/usr/bin/bash

while [ true ]

do 
	ping -c 1 google.com &>2

	if [ $? -ne 0  ]
	then 
		echo "Ping failed. Waiting for network up."
	else
	
		
		ip=$(/usr/bin/dig +short myip.opendns.com @resolver3.opendns.com.)
#i know. this looks like an exercise in cut, but it's not. Just the simplest way I could think of.
up=`uptime | cut -d',' -f1`
logins=`uptime | cut -d',' -f2`
load=`uptime | cut -d',' -f3-`
users=`who | cut -d' ' -f1-4,14`
		echo -e "to: aimcorp2018@gmail.com\nSubject:$(hostname) is online.\nPublic IP is $ip\n\nSERVER TIME/UPTIME: $up\n\nLOGINS: $logins\n$users\n\nLOAD: $load" | /usr/sbin/sendmail -t -f root 

		exit 0
	fi
	sleep 1

done
